let telegramChat = require('./telegramChat.js');

let list = [{
    id: 373228139,
    user_name: 'upgiItDepartment',
    first_name: '統義玻璃',
    last_name: '資訊課',
    status: ['admin', 'user'],
    email: '',
    joinedGroupIDList: [
        telegramChat.list[0].id,
        telegramChat.list[1].id
    ],
    upgEmployeeID: ''
}, {
    id: 396145285,
    user_name: 'chiayutsaipersonal',
    first_name: 'Chia-Yu',
    last_name: 'Tsai',
    status: ['admin', 'user'],
    email: 'junior@upgi.com.tw',
    joinedGroupIDList: [
        telegramChat.list[0].id,
        telegramChat.list[1].id
    ],
    upgEmployeeID: '05060001'
}, {
    id: 241630569,
    user_name: 'junior_upgi',
    first_name: '佳佑',
    last_name: '蔡',
    status: ['admin', 'user'],
    email: 'junior@upgi.com.tw',
    joinedGroupIDList: [
        telegramChat.list[0].id,
        telegramChat.list[1].id
    ],
    upgEmployeeID: '05060001'
}, {
    id: 252069370,
    user_name: 'upgi_spark',
    first_name: '于斌',
    last_name: '林',
    status: ['admin', 'user'],
    email: 'it@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '16080003'
}, {
    id: 240006091,
    user_name: 'Ray0626',
    first_name: '治儒',
    last_name: '陳',
    status: ['user'],
    email: '',
    joinedGroupList: [],
    upgEmployeeID: '15050003'
}, {
    id: 261033177,
    user_name: 'Samhuang',
    first_name: '顯鈞',
    last_name: '黃',
    status: ['user'],
    email: '',
    joinedGroupList: [],
    upgEmployeeID: '16010002'
}, {
    id: 270251655,
    username: 'Wenghungta',
    first_name: '宏達',
    last_name: '翁',
    status: ['admin', 'user'],
    email: 'mis@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '99030003'
}, {
    id: 243538978,
    username: 'upgfurnace',
    first_name: '高榮',
    last_name: '張',
    status: ['user'],
    email: 'furnace@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '10120001'
}, {
    id: 260499091,
    username: 'Jacobchuang',
    first_name: '再興',
    last_name: '莊',
    status: ['user'],
    email: 'jacob@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '88080073'
}, {
    id: 297313252,
    username: 'UPGElle',
    first_name: '世玲',
    last_name: '翁',
    status: ['user'],
    email: 'prodctrl@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '07100003'
}, {
    id: 280941957,
    username: 'upgijacklin',
    first_name: '建睿',
    last_name: '林',
    status: ['user'],
    email: 'jacklin@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '94030001'
}, {
    id: 269370139,
    username: 'Oliviachen0227',
    first_name: '逸樺',
    last_name: '陳',
    status: ['user'],
    email: 'olivia@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '06070004'
}, {
    id: 299863805,
    username: 'Srthhgdy',
    first_name: '慶瑞',
    last_name: '王',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '91050006'
}, {
    id: 275846005,
    username: 'Shuhualee',
    first_name: '淑華',
    last_name: '李',
    status: ['user'],
    email: 'shuhua.lee@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '95090001'
}, {
    id: 289590897,
    username: 'Janice2232',
    first_name: '芳伊',
    last_name: '郭',
    status: ['user'],
    email: 'janice@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '13070002'
}, {
    id: 285600420,
    username: 'Phoebe0830',
    first_name: '珈慧',
    last_name: '廖',
    status: ['user'],
    email: 'phoebe@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '12090006'
}, {
    id: 225829917,
    username: 'UPGI_ChungChou',
    first_name: 'Lin',
    last_name: 'Chung Chou',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '11020002'
}, {
    id: 277098776,
    username: 'David0937614299',
    first_name: '志鑫',
    last_name: '林',
    status: ['user'],
    email: 'davidlin@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '03090001'
}, {
    id: 281948128,
    username: 'EvitaUPG',
    first_name: '文君',
    last_name: '莊',
    status: ['user'],
    email: 'evita@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '12020012'
}, {
    id: 281458056,
    username: 'Jeffrey_upgi',
    first_name: '政宏',
    last_name: '蔡',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '11080005'
}, {
    id: 290457488,
    username: 'upgi_shen0445',
    first_name: '昌言',
    last_name: '沈',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '03070001'
}, {
    id: 288942651,
    username: 'hugo0831',
    first_name: '雨利',
    last_name: '陳',
    status: ['user'],
    email: 'hugo@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '93120001'
}, {
    id: 236207790,
    username: 'jack5447',
    first_name: '游',
    last_name: '閔楠',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '07120002'
}, {
    id: 254848482,
    username: 'yuraHou',
    first_name: '孟均',
    last_name: '侯',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '16030003'
}, {
    id: 282526890,
    username: 'upgelma',
    first_name: '毓馨',
    last_name: '陳',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '07080001'
}, {
    id: 267702707,
    username: 'HouseChen',
    first_name: 'Wayne',
    last_name: 'Chen',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '07040001'
}, {
    id: 277535543,
    username: 'maviscwling',
    first_name: '婉伶',
    last_name: '趙',
    status: ['user'],
    email: 'mavis@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '08030005'
}, {
    id: 288913691,
    username: 'Gehhxhsg',
    first_name: '志如',
    last_name: '陳',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '99040008'
}, {
    id: 295200881,
    username: 'UPGChristina',
    first_name: '綺緁',
    last_name: '林',
    status: ['user'],
    joinedGroupList: [],
    upgEmployeeID: '14060007'
}, {
    id: undefined,
    username: 'RDruby',
    first_name: '宜如',
    last_name: '林',
    status: ['user'],
    email: 'design2@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '99040007'
}, {
    id: 279766628,
    username: 'FrancisLiu',
    first_name: '得臣',
    last_name: '劉',
    status: ['user'],
    email: 'francis@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '16080001'
}, {
    id: 288237926,
    username: 'Raquel770302',
    first_name: '宛儒',
    last_name: '李',
    status: ['user'],
    email: 'emma@upgi.com.tw',
    joinedGroupList: [],
    upgEmployeeID: '16060001'
}];

function getUserID(userName) {
    let chat_id;
    list.forEach(function(userObject) {
        if (userObject.last_name + userObject.first_name === userName) {
            chat_id = userObject.id;
        }
    });
    return chat_id;
}

module.exports = {
    getUserID: getUserID,
    list: list
};
